
# Last updated: 2026-02-04 16:36 UTC
name: Build and Release Installer


on:
  release:
    types: [published]



jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Download Ninja
        run: |
          curl -L -o ninja-win.zip https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
          unzip ninja-win.zip -d ninja_bin
          echo "${{ github.workspace }}/ninja_bin" >> $GITHUB_PATH

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Install LLVM
        run: choco install llvm -y

      - name: Install NSIS
        run: choco install nsis -y


      - name: Extract version from tag
        id: get_version
        run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Configure (Release)
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_VERSION=${{ env.TAG_VERSION }}

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Package with CPack
        run: cpack --config build/CPackConfig.cmake

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.exe
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
